CREATE DATABASE Calories;
USE Calories;

CREATE TABLE Nutrition (
	idProduct INT UNSIGNED NOT NULL AUTO_INCREMENT,
	ProductName VARCHAR(100) NOT NULL,
	Proteins FLOAT UNSIGNED,
	Fats FLOAT UNSIGNED,
	Carbohydrate FLOAT UNSIGNED,
	Calories FLOAT UNSIGNED,
	PRIMARY KEY(idProduct),
	UNIQUE KEY(ProductName)  
) DEFAULT CHARSET = latin1;


CREATE TABLE Consumption (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	idProduct INT UNSIGNED NOT NULL,
	Weight FLOAT UNSIGNED,
	`Date` DATE NOT NULL,
	PRIMARY KEY(id),
	KEY(`Date`)  
) DEFAULT CHARSET = latin1;